services:
  web:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build: .
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm","run","test"]
    tty: true
    stdin_open: true